# Worksheets per report 
ws <- list(CSSEA = data.frame(schedule = c("Home", 
                                           paste0("Q", 1:3), 
                                           paste0("A", 1:5),
                                           paste0(rep(c("B", "C", "D"), each = 2), 1:2), 
                                           paste0("E", 1:5)),
                              category = c("Home",
                                           rep("Questionnaire", 3),
                                           rep("Bargaining Unit", 5),
                                           rep("Non-Union", 2),
                                           rep("Management & Excluded", 2),
                                           rep("Summary", 2),
                                           rep("Terminations", 5))),
           nonCSSEA = data.frame(schedule = c("Home", 
                                              paste0("Q", 1:3), 
                                              paste0(rep(c("N", "M", "B", "S"), each = 2), 1:2), 
                                              paste0("T", 1:4)),
                                 category = c("Home",
                                              rep("Questionnaire", 3),
                                              rep("Bargaining Unit", 2),
                                              rep("Non-Union", 2),
                                              rep("Management & Excluded", 2),
                                              rep("Summary", 2),
                                              rep("Terminations", 4))))

cnames <- list(CSSEA = list(employeeType = c("PF_BU", "PF_Mgmnt", "PF_NU", "NPF_BU", "NPF_Mgmnt", "NPF_NU"),
                            terminations = c("BU_Paraprofessional", "BU_Benchmark", "BU_Delegated", "NU_Paraprofessional", "NU_Benchmark", "NU_Delegated", "Management"),
                            A1 = c("PositionType", "Classification_1", "GridLvl_1", "Classification_2", "GridLvl_2", "Eff_GridLvl",
                                   "RegularOrCasual", "YrlyStdHrs", "NPF_Hrs_StraightTime", "NPF_HrlyWage", "PF_Hrs_StraightTime", 
                                   paste0("PF_Hrs_S", 1:4), "PF_Hrs_S4+", "PF_HrlyWage", "SSO_NPF_Hrs", "SSO_NPF_HrlyWage", "SSO_PF_Hrs", "SSO_PF_HrlyWage"),
                            A2 = c("PositionType", "Classification_1", "Classification_2", "RegularOrCasual", "YrlyStdHrs",
                                   "NPF_Active", "PF_Active", "PF_LTD", "PF_WCB", "PF_MPLeave", "PF_UnionLeave", "PF_Other", 
                                   "Vacant", "Terminated", "NewHiresExternal", "NewHiresInternal", "Backfill_StraightTimeHrs", "Bacfill_pct"),
                            A4 = c("PositionType", "RegularOrCasual", "YrlyStdHrs", "Eff_GridLvl", "NPF_Hrs_StraightTime", "NPF_HrlyWage", 
                                   "PF_Hrs_StraightTime", paste0("PF_Hrs_S", 1:5), "NPF_Active", "PF_Active", "PF_LTD", "PF_WCB", "PF_MPLeave",
                                   "PF_UnionLeave", "PF_Other", "Vacant", "Terminated", "NewHiresExternal", "NewHiresInternal", 
                                   "Backfill_StraightTimeHrs", "Bacfill_pct", "SSO_NPF_Hrs", "SSO_NPF_HrlyWage", "SSO_PF_Hrs", "SSO_PF_HrlyWage")),
               nonCSSEA = list(employeeType = c("PF_NU", "PF_Mgmnt", "PF_BU", "NPF_NU", "NPF_Mgmnt", "NPF_BU"),
                               terminations = c("NU_Paraprofessional", "Nu_Benchmark", "NU_Delegated", "Management", "BU_Paraprofessional", "BU_Benchmark", "BU_Delegated")),
               universal = list(home = c("Funder", "Funding_Union", "Funding_NonUnion", "Total Funding", "Pct_Funding_Union", "Pct_Funding_NonUnion", "Pct_Funding_Tot", "N_UnionContracts", "N_NonUnionContracts", "N_TotalContracts"),
                                SSO_Table = c("Name", "Site_ID", "Classification", "FTE"),
                                SI_Table = c("Classification", "Count"),
                                NU_1 = c("Classification", "RegularOrCasual", "YrlyStdHrs", "NPF_Hrs_StraightTime", "PF_Hrs_StraightTime", "NPF_HrlyWage", "PF_HrlyWage", "NPF_Active", "PF_Active", "PF_LTD", "PF_WCB", "PF_MPLeave", "PF_Other", "Vacant", "Terminated", "NewHiresExternal", "NewHiresInternal", "Backfill_StraightTimeHrs", "Bacfill_pct", "SSO_NPF_Hrs", "SSO_NPF_HrlyWage", "SSO_PF_Hrs", "SSO_PF_HrlyWage"),
                                M1_C1 = c("Classification", "Gender", "AvgAnnualSalary", "NPF_Payroll", "NPF_Expenses", "PF_Payroll", "PF_Expenses", "NPF_Hrs", "PF_Hrs", "NPF_Active", "PF_Active", "PF_LTD", "PF_WCB", "PF_MPLeave", "PF_Other", "Vacant", "Terminated", "NewHiresExternal", "NewHiresInternal", "Backfill_StraightTimeHrs", "Bacfill_pct", "SSO_NPF_Hrs", "SSO_NPF_HrlyWage", "SSO_PF_Hrs", "SSO_PF_HrlyWage"),
                                ME_demographics = c("LengthofService", "All", "", "ED_Only", "", "Age", "AgeGender_M", "AgeGender_F", "AgeGender_GD", "", "", "", "", "", "Benefit Type", "Part_Single", "Part_Couple", "Part_Family", "NonPart_Eligible", "NonPart_Ineligible"),
                                demographics = c("LengthofService", "Seniority_Regular", "", "Seniority_Casual", "", "Age", "AgeGender_Regular_M", "AgeGender_Regular_F", "AgeGender_Regular_GD", "", "AgeGender_Casual_M", "AgeGender_Casual_F", "AgeGender_Casual_GD", "", "Benefit Type", "Part_Single", "Part_Couple", "Part_Family", "NonPart_Eligible", "NonPart_Ineligible"),
                                timeToFill = c("Classification", "Classification Sub-type", "Days to Fill")))
